format = """
$username\
$hostname\
$git_branch\
$git_state\
$git_commit\
$kubernetes\
$docker_context\
$package\
$cmake\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nodejs\
$perl\
$php\
$python\
$rlang\
$ruby\
$rust\
$scala\
$swift\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$crystal\
$custom\
$line_break\
$directory\
$jobs\
$status\
$character
"""

command_timeout = 2000

[aws]
symbol = "aws"
disabled = true

[conda]
symbol = " "

[directory]
read_only = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = ".py "

[ruby]
symbol = ".rb "

[rust]
symbol = ".rs "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "

[nodejs]
symbol = "node "
version_format = "v${major}.${minor}"
